---
:mailboxes:
  -
    :email: "codingninjatesting@gmail.com"
    :password: "alms007alms"
    :name: "inbox"
    :delivery_method: postback
    :delivery_options:
      :delivery_url: "http://codingninjatest.herokuapp.com/inbox"
      :delivery_token: "abcdefg"
